### ISSUE TITLE
Visualixir does not load with Node 6 (6.5.0)

### ISSUE THREAD

**Issue by debajit** [koudelka/visualixir#12]
When I start it using the instructions given, all i see is this:

![Screenshot](https://d17oy1vhnax1f7.cloudfront.net/items/1u1H0T1u0c1K360D0D28/localhost_4000.png)

When I enter the name of my other node, that does not show anything either.

I tried using `--name` in place of `--sname` but that did not work either.

----

This may or may not be related, but I see the following errors in the console:

```bash
% elixir --name visualixir --hidden -S mix phoenix.server

[warn] using the :root endpoint configuration for watchers is deprecated.
Pass the :cd option at the end of your watcher argument list in config/dev.exs. For example:

    watchers: [node: ["node_modules/brunch/bin/brunch", "watch", "--stdin",
               cd: Path.expand("../", __DIR__)]]

[info] Running Visualixir.Endpoint with Cowboy using http://localhost:4000
(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.

==== JS stack trace =========================================

Security context: 0x1f645cfcfb51 <JS Object>#0#
    1: .node [module.js:583] [pc=0xd7e023ae664] (this=0x2c8c45dcd279 <an Object with map 0x28a690b1ad01>#1#,module=0xed8a1adf771 <a Module with map 0x28a690b1bc21>#2#,filename=0xed8a1add079 <String[81]: /Users/debajita/Developer/visualixir/node_modules/fsevents/build/Release/fse.node>)
    2: load [module.js:473] [pc=0xd7e0233d5d2] (this=0xed8a1adf771 <a Module with map 0x28a690b1bc21>#2#,filename
==== JS stack trace =========================================

Security context: 0x1f645cfcfb51 <JS Object>#0#
    1: .node [module.js:583] [pc=0xd7e023ae664] (this=0x2c8c45dcd279 <an Object with map 0x28a690b1ad01>#1#,module=0xed8a1adf771 <a Module with map 0x28a690b1bc21>#2#,filename=0xed8a1add079 <String[81]: /Users/debajita/Developer/visualixir/node_modules/fsevents/build/Release/fse.node>)
    2: load [module.js:473] [pc=0xd7e0233d5d2] (this=0xed8a1adf771 <a Module with map 0x28a690b1bc21>#2#,filename/Users/debajita/Developer/visualixir/node_modules/brunch/lib/fs_utils/file_list.js:77
        return path.match(test);
                    ^

TypeError: Cannot assign to read only property 'lastIndex' of object '[object RegExp]'
  at RegExp.exec (native)
  at RegExp.[Symbol.match] (native)
  at String.match (native)
  at FileList.module.exports.FileList.isIgnored (/Users/debajita/Developer/visualixir/node_modules/brunch/lib/fs_utils/file_list.js:77:21)
  at /Users/debajita/Developer/visualixir/node_modules/
``` 

When I fix the 'cd' issue reported, I still see the following errors

```bash
% elixir --name visualixir --hidden -S mix phoenix.server
[info] Running Visualixir.Endpoint with Cowboy using http://localhost:4000
(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.

==== JS stack trace =========================================

Security context: 0x146707acfb51 <JS Object>#0#
    1: .node [module.js:583] [pc=0x21313ceac884] (this=0x222257612051 <an Object with map 0x2d2808e1ad01>#1#,module=0xdf1812e7a19 <a Module with map 0x2d2808e1bc21>#2#,filename=0xdf1812e5321 <String[81]: /Users/debajita/Developer/visualixir/node_modules/fsevents/build/Release/fse.node>)
    2: load [module.js:473] [pc=0x21313ce3d5d2] (this=0xdf1812e7a19 <a Module with map 0x2d2808e1bc21>#2#,filena
==== JS stack trace =========================================

Security context: 0x146707acfb51 <JS Object>#0#
    1: .node [module.js:583] [pc=0x21313ceac884] (this=0x222257612051 <an Object with map 0x2d2808e1ad01>#1#,module=0xdf1812e7a19 <a Module with map 0x2d2808e1bc21>#2#,filename=0xdf1812e5321 <String[81]: /Users/debajita/Developer/visualixir/node_modules/fsevents/build/Release/fse.node>)
    2: load [module.js:473] [pc=0x21313ce3d5d2] (this=0xdf1812e7a19 <a Module with map 0x2d2808e1bc21>#2#,filena/Users/debajita/Developer/visualixir/node_modules/brunch/lib/fs_utils/file_list.js:77
        return path.match(test);
                    ^

TypeError: Cannot assign to read only property 'lastIndex' of object '[object RegExp]'
  at RegExp.exec (native)
  at RegExp.[Symbol.match] (native)
  at String.match (native)
  at FileList.module.exports.FileList.isIgnored (/Users/debajita/Developer/visualixir/node_modules/brunch/lib/fs_utils/file_list.js:77:21)
  at /Users/debajita/Developer/visualixir/node_modules/
```

Does visualixir even work on macOS? I'd like to know if this is a known bug, or what I'm doing wrong.

**Comment by koudelka** [comment]
Hey there, I'm sorry, I don't have the latest installed due to work. :(

It looks like the version of node that you're on is getting angry.

I've got 5.9.1 (I never use node, I don't know if that's recent or what)

**Comment by debajit** [comment]
Downgrading to Node 5 (5.12.0 in my case) fixes the issue for me. Thanks a ton :) I've upgraded the title to reflect this.
